use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Config {
    /// Wireless interface; auto-detected if unset.
    pub interface: Option<String>,
    #[serde(default)]
    pub router: RouterConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouterConfig {
    #[serde(default = "default_true")]
    pub enabled: bool,
    #[serde(default = "default_router_url")]
    pub base_url: String,
    #[serde(default = "default_username")]
    pub username: String,
    /// Prefer `password_env` or MYWIFISTATS_ROUTER_PASSWORD.
    pub password: Option<String>,
    /// Name of env var holding the password (default MYWIFISTATS_ROUTER_PASSWORD).
    pub password_env: Option<String>,
    /// Backend kind; only "zte_f670l" for now.
    #[serde(default = "default_backend")]
    pub backend: String,
}

fn default_true() -> bool {
    true
}
fn default_router_url() -> String {
    "http://192.168.1.1".into()
}
fn default_username() -> String {
    "admin".into()
}
fn default_backend() -> String {
    "zte_f670l".into()
}

impl Default for RouterConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            base_url: default_router_url(),
            username: default_username(),
            password: None,
            password_env: None,
            backend: default_backend(),
        }
    }
}

impl Config {
    pub fn config_path() -> PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join("mywifistats")
            .join("config.toml")
    }

    pub fn load() -> Result<Self> {
        let path = Self::config_path();
        let mut cfg = if path.exists() {
            let text = fs::read_to_string(&path)
                .with_context(|| format!("reading config {}", path.display()))?;
            toml::from_str(&text).with_context(|| format!("parsing config {}", path.display()))?
        } else {
            Config::default()
        };

        // Env overrides (runtime only — not written back unless saved via setup)
        if let Ok(iface) = std::env::var("MYWIFISTATS_INTERFACE") {
            if !iface.is_empty() {
                cfg.interface = Some(iface);
            }
        }
        if let Ok(url) = std::env::var("MYWIFISTATS_ROUTER_URL") {
            if !url.is_empty() {
                cfg.router.base_url = url;
            }
        }
        if let Ok(user) = std::env::var("MYWIFISTATS_ROUTER_USER") {
            if !user.is_empty() {
                cfg.router.username = user;
            }
        }
        if let Ok(en) = std::env::var("MYWIFISTATS_ROUTER_ENABLED") {
            cfg.router.enabled = matches!(en.to_ascii_lowercase().as_str(), "1" | "true" | "yes");
        }

        Ok(cfg)
    }

    /// Persist config to disk (mode 0600). Does not include env-only overrides unless already in struct.
    pub fn save(&self) -> Result<()> {
        let path = Self::config_path();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }

        // Hand-written TOML so comments survive and empty options look clean.
        let mut out = String::new();
        out.push_str("# mywifistats configuration\n");
        out.push_str("# Generated by `mywifistats setup` — edit freely or re-run setup.\n\n");
        match &self.interface {
            Some(iface) if !iface.is_empty() => {
                out.push_str(&format!("interface = \"{}\"\n\n", escape_toml(iface)));
            }
            _ => {
                out.push_str("# interface = \"wlan0\"  # leave unset for auto-detect\n\n");
            }
        }
        out.push_str("[router]\n");
        out.push_str(&format!("enabled = {}\n", self.router.enabled));
        out.push_str(&format!(
            "base_url = \"{}\"\n",
            escape_toml(&self.router.base_url)
        ));
        out.push_str(&format!(
            "username = \"{}\"\n",
            escape_toml(&self.router.username)
        ));
        out.push_str(&format!(
            "backend = \"{}\"\n",
            escape_toml(&self.router.backend)
        ));
        if let Some(env) = &self.router.password_env {
            if !env.is_empty() {
                out.push_str(&format!("password_env = \"{}\"\n", escape_toml(env)));
            }
        }
        match &self.router.password {
            Some(p) if !p.is_empty() => {
                out.push_str(&format!("password = \"{}\"\n", escape_toml(p)));
            }
            _ => {
                out.push_str(
                    "# password = \"...\"\n# Or: export MYWIFISTATS_ROUTER_PASSWORD='...'\n",
                );
            }
        }

        fs::write(&path, out).with_context(|| format!("writing {}", path.display()))?;
        let mut perms = fs::metadata(&path)?.permissions();
        perms.set_mode(0o600);
        fs::set_permissions(&path, perms)?;
        Ok(())
    }

    pub fn router_password(&self) -> Option<String> {
        let env_name = self
            .router
            .password_env
            .as_deref()
            .unwrap_or("MYWIFISTATS_ROUTER_PASSWORD");
        if let Ok(p) = std::env::var(env_name) {
            if !p.is_empty() {
                return Some(p);
            }
        }
        self.router
            .password
            .clone()
            .filter(|p| !p.is_empty())
    }

    pub fn needs_setup_hint(&self) -> bool {
        self.router.enabled && self.router_password().is_none()
    }
}

fn escape_toml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
